spring:
  application:
    name: flowlinkbackend
  data:
    mongodb:
      username: root
      password: example
      database: flowlink
      host: localhost
      port: 27017
      authentication-database: admin
service:
  auth:
    accessTokenExpiration: 86400
    refreshTokenExpiration: 2592000
    # change it for production deploy
    secret: "a6l9vg2PrYRSFcXZBOUnECJoiBxjn4lE-hDxrIpKO67yPBPqFypQQBsfT7GiyIpw8_gzvi2XQHWCgg0nEJa-Idyo6jv6ylRBxy3uxmc9E0l2cTfTznSNNpm1VGM8u67r72glGMfVD7fBbIoFFRxbF-zWXoRj8ULlTcGZjVZc0GimUeT0AqT83kK6m-rh-vsNTF_X_ROErumRemUGNZiUcrhRY5YePx8hRWJvYq7eDntZM_wdE5I-jnNhadkkyfcy5Eyy1FskhQWnfe2YOygwkfcTh2NqjMtfQQyBZyjnLOHi_IDPPJ4TBJqIesf1U-moCuNxgJ79SNx4B9NHK_jpXgcdu__yVE1Z-MeTam9_A0JOjvxyB3amYFAg0-gLxAq1bW3KA7iER2WbGUtuPI_cW1JgDW2Raeg8NiuwVSrQEDjhEVwhgU-uC9BQ76k-XHgOz3ne41h9QZnQE5B3V4Go8VzdqHdUqutYTR3ts630vgdlRqXXKmbTytZNVqsUNRHQudqQlPN_I4kT6gjBBRDZY7_VRMD5lm70-rhNTSyKRlrQqGLIGr5g9fQ_Gld1CssogWBAbU7bHoMVT7yLD8o32u9yxAuAqKbb-NfOhPzXOAlO8P3tyYKX09Og_UTvoiL_2DMsfYb93BpVaQlx94A_T4VDUk7i6E-SLNLm6VzMXtA="
server:
  port: 8081
llm-provider:
  token: your_token
  host: https://openrouter.ai/api/v1/