spring:
  application:
    name: flowlinkbackend
  data:
    mongodb:
      username: root
      password: example
      database: flowlink
      host: localhost
      port: 27017
      authentication-database: admin
service:
  auth:
    accessTokenExpiration: 86400
    refreshTokenExpiration: 2592000
    # change it for production deploy
    secret: 'secret'
server:
  port: 8081
s3:
  host: https://bondsaver.s3.cloud.ru
  # change it for production deploy
  accessKey: 'accesskey'
  # change it for production deploy
  secretKey: 'secretKey'
  bucket: bondsaver
llm-provider:
  # change it for production deploy
  token: 'token'
  host: https://openrouter.ai/api/v1/